-- Vanilla Works START
    
    ['vwe_550ss'] = {
        ['name'] = 'vwe_550ss',   
        ['model'] = 'vwe_550ss',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_550ss',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_adder1'] = {
        ['name'] = 'vwe_adder1',       
        ['model'] = 'vwe_adder1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_adder1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_admiral1'] = {
        ['name'] = 'vwe_admiral1',   
        ['model'] = 'vwe_admiral1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_admiral1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_alamo1'] = {
        ['name'] = 'vwe_alamo1',   
        ['model'] = 'vwe_alamo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_alamo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_alamo2'] = {
        ['name'] = 'vwe_alamo2',   
        ['model'] = 'vwe_alamo2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_alamo2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_alamo3'] = {
        ['name'] = 'vwe_alamo3',   
        ['model'] = 'vwe_alamo3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_alamo3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_annihilator1'] = {
        ['name'] = 'vwe_annihilator1',   
        ['model'] = 'vwe_annihilator1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_annihilator1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ardent1'] = {
        ['name'] = 'vwe_ardent1',   
        ['model'] = 'vwe_ardent1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ardent1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_argento1'] = {
        ['name'] = 'vwe_argento1',   
        ['model'] = 'vwe_argento1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_argento1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ariant1'] = {
        ['name'] = 'vwe_ariant1',   
        ['model'] = 'vwe_ariant1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ariant1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_armordillo1'] = {
        ['name'] = 'vwe_armordillo1',   
        ['model'] = 'vwe_armordillo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_armordillo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_banshee1'] = {
        ['name'] = 'vwe_banshee1',   
        ['model'] = 'vwe_banshee1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_banshee1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_barracks1'] = {
        ['name'] = 'vwe_barracks1',   
        ['model'] = 'vwe_barracks1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_barracks1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_benson1'] = {
        ['name'] = 'vwe_benson1',   
        ['model'] = 'vwe_benson1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_benson1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_besra1'] = {
        ['name'] = 'vwe_besra1',   
        ['model'] = 'vwe_besra1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_besra1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bfinjection1'] = {
        ['name'] = 'vwe_bfinjection1',   
        ['model'] = 'vwe_bfinjection1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bfinjection1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_biff1'] = {
        ['name'] = 'vwe_biff1',   
        ['model'] = 'vwe_biff1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_biff1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_biff2'] = {
        ['name'] = 'vwe_biff2',   
        ['model'] = 'vwe_biff2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_biff2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bison1'] = {
        ['name'] = 'vwe_bison1',   
        ['model'] = 'vwe_bison1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bison1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bison2'] = {
        ['name'] = 'vwe_bison2',   
        ['model'] = 'vwe_bison2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bison2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_blade1'] = {
        ['name'] = 'vwe_blade1',   
        ['model'] = 'vwe_blade1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_blade1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_blazer1'] = {
        ['name'] = 'vwe_blazer1',   
        ['model'] = 'vwe_blazer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_blazer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_boattrailer1'] = {
        ['name'] = 'vwe_boattrailer1',   
        ['model'] = 'vwe_boattrailer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_boattrailer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcat1'] = {
        ['name'] = 'vwe_bobcat1',   
        ['model'] = 'vwe_bobcat1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcat1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcat2'] = {
        ['name'] = 'vwe_bobcat2',   
        ['model'] = 'vwe_bobcat2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcat2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcat3'] = {
        ['name'] = 'vwe_bobcat3',   
        ['model'] = 'vwe_bobcat3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcat3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcatxl1'] = {
        ['name'] = 'vwe_bobcatxl1',   
        ['model'] = 'vwe_bobcatxl1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcatxl1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcatxl2'] = {
        ['name'] = 'vwe_bobcatxl2',   
        ['model'] = 'vwe_bobcatxl2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcatxl2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bobcatxl3'] = {
        ['name'] = 'vwe_bobcatxl3',   
        ['model'] = 'vwe_bobcatxl3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bobcatxl3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_boxville1'] = {
        ['name'] = 'vwe_boxville1',   
        ['model'] = 'vwe_boxville1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_boxville1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_boxville2'] = {
        ['name'] = 'vwe_boxville2',   
        ['model'] = 'vwe_boxville2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_boxville2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_brigham1'] = {
        ['name'] = 'vwe_brigham1',   
        ['model'] = 'vwe_brigham1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_brigham1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo1'] = {
        ['name'] = 'vwe_buffalo1',   
        ['model'] = 'vwe_buffalo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo2'] = {
        ['name'] = 'vwe_buffalo2',   
        ['model'] = 'vwe_buffalo2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo3'] = {
        ['name'] = 'vwe_buffalo3',   
        ['model'] = 'vwe_buffalo3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo4'] = {
        ['name'] = 'vwe_buffalo4',   
        ['model'] = 'vwe_buffalo4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo5'] = {
        ['name'] = 'vwe_buffalo5',   
        ['model'] = 'vwe_buffalo5',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo5',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo6'] = {
        ['name'] = 'vwe_buffalo6',   
        ['model'] = 'vwe_buffalo6',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo6',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_buffalo7'] = {
        ['name'] = 'vwe_buffalo7',   
        ['model'] = 'vwe_buffalo7',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_buffalo7',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_burrito1'] = {
        ['name'] = 'vwe_burrito1',   
        ['model'] = 'vwe_burrito1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_burrito1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_burrito2'] = {
        ['name'] = 'vwe_burrito2',   
        ['model'] = 'vwe_burrito2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_burrito2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_bus1'] = {
        ['name'] = 'vwe_bus1',   
        ['model'] = 'vwe_bus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_bus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_caddy1'] = {
        ['name'] = 'vwe_caddy1',   
        ['model'] = 'vwe_caddy1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_caddy1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_caracara1'] = {
        ['name'] = 'vwe_caracara1',   
        ['model'] = 'vwe_caracara1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_caracara1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cartrailer1'] = {
        ['name'] = 'vwe_cartrailer1',   
        ['model'] = 'vwe_cartrailer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cartrailer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cartrailer2'] = {
        ['name'] = 'vwe_cartrailer2',   
        ['model'] = 'vwe_cartrailer2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cartrailer2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_castella1'] = {
        ['name'] = 'vwe_castella1',   
        ['model'] = 'vwe_castella1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_castella1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cavalcade1'] = {
        ['name'] = 'vwe_cavalcade1',   
        ['model'] = 'vwe_cavalcade1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cavalcade1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cbus1'] = {
        ['name'] = 'vwe_cbus1',   
        ['model'] = 'vwe_cbus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cbus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cerberus1'] = {
        ['name'] = 'vwe_cerberus1',   
        ['model'] = 'vwe_cerberus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cerberus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cerberus2'] = {
        ['name'] = 'vwe_cerberus2',   
        ['model'] = 'vwe_cerberus2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cerberus2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cerberus3'] = {
        ['name'] = 'vwe_cerberus3',   
        ['model'] = 'vwe_cerberus3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cerberus3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cerberus4'] = {
        ['name'] = 'vwe_cerberus4',   
        ['model'] = 'vwe_cerberus4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cerberus4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cerberus5'] = {
        ['name'] = 'vwe_cerberus5',   
        ['model'] = 'vwe_cerberus5',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cerberus5',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cheetah1'] = {
        ['name'] = 'vwe_cheetah1',   
        ['model'] = 'vwe_cheetah1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cheetah1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_club1'] = {
        ['name'] = 'vwe_club1',   
        ['model'] = 'vwe_club1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_club1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cogcabrio1'] = {
        ['name'] = 'vwe_cogcabrio1',   
        ['model'] = 'vwe_cogcabrio1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cogcabrio1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_cognoscenti1'] = {
        ['name'] = 'vwe_cognoscenti1',   
        ['model'] = 'vwe_cognoscenti1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_cognoscenti1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_comet1'] = {
        ['name'] = 'vwe_comet1',   
        ['model'] = 'vwe_comet1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_comet1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_comet2'] = {
        ['name'] = 'vwe_comet2',   
        ['model'] = 'vwe_comet2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_comet2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_contender1'] = {
        ['name'] = 'vwe_contender1',   
        ['model'] = 'vwe_contender1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_contender1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_contender2'] = {
        ['name'] = 'vwe_contender2',   
        ['model'] = 'vwe_contender2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_contender2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_contender3'] = {
        ['name'] = 'vwe_contender3',   
        ['model'] = 'vwe_contender3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_contender3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_contender4'] = {
        ['name'] = 'vwe_contender4',   
        ['model'] = 'vwe_contender4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_contender4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_contender5'] = {
        ['name'] = 'vwe_contender5',   
        ['model'] = 'vwe_contender5',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_contender5',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_coquette1'] = {
        ['name'] = 'vwe_coquette1',   
        ['model'] = 'vwe_coquette1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_coquette1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_coquette2'] = {
        ['name'] = 'vwe_coquette2',   
        ['model'] = 'vwe_coquette2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_coquette2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_coquette3'] = {
        ['name'] = 'vwe_coquette3',   
        ['model'] = 'vwe_coquette3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_coquette3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_coyote1'] = {
        ['name'] = 'vwe_coyote1',   
        ['model'] = 'vwe_coyote1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_coyote1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_coyote2'] = {
        ['name'] = 'vwe_coyote2',   
        ['model'] = 'vwe_coyote2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_coyote2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_deluxo1'] = {
        ['name'] = 'vwe_deluxo1',   
        ['model'] = 'vwe_deluxo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_deluxo1',   
        ['shop'] = 'pdm',   
    },       
    ['vwe_dingo1'] = {
        ['name'] = 'vwe_dingo1',   
        ['model'] = 'vwe_dingo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dingo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dingo2'] = {
        ['name'] = 'vwe_dingo2',   
        ['model'] = 'vwe_dingo2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dingo2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dloader1'] = {
        ['name'] = 'vwe_dloader1',   
        ['model'] = 'vwe_dloader1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dloader1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dominator1'] = {
        ['name'] = 'vwe_dominator1',   
        ['model'] = 'vwe_dominator1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dominator1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dubsta1'] = {
        ['name'] = 'vwe_dubsta1',   
        ['model'] = 'vwe_dubsta1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dubsta1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dukes1'] = {
        ['name'] = 'vwe_dukes1',   
        ['model'] = 'vwe_dukes1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dukes1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_dukes2'] = {
        ['name'] = 'vwe_dukes2',   
        ['model'] = 'vwe_dukes2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_dukes2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_elegy1'] = {
        ['name'] = 'vwe_elegy1',   
        ['model'] = 'vwe_elegy1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_elegy1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_elegy2'] = {
        ['name'] = 'vwe_elegy2',   
        ['model'] = 'vwe_elegy2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_elegy2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_elena1'] = {
        ['name'] = 'vwe_elena1',   
        ['model'] = 'vwe_elena1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_elena1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_esperanto1'] = {
        ['name'] = 'vwe_esperanto1',   
        ['model'] = 'vwe_esperanto1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_esperanto1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_euphoria1'] = {
        ['name'] = 'vwe_euphoria1',   
        ['model'] = 'vwe_euphoria1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_euphoria1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_euros1'] = {
        ['name'] = 'vwe_euros1',   
        ['model'] = 'vwe_euros1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_euros1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_executioner1'] = {
        ['name'] = 'vwe_executioner1',   
        ['model'] = 'vwe_executioner1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_executioner1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_executioner2'] = {
        ['name'] = 'vwe_executioner2',   
        ['model'] = 'vwe_executioner2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_executioner2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_executioner3'] = {
        ['name'] = 'vwe_executioner3',   
        ['model'] = 'vwe_executioner3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_executioner3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_feroci1'] = {
        ['name'] = 'vwe_feroci1',   
        ['model'] = 'vwe_feroci1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_feroci1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_flatbed1'] = {
        ['name'] = 'vwe_flatbed1',   
        ['model'] = 'vwe_flatbed1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_flatbed1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_fugitive1'] = {
        ['name'] = 'vwe_fugitive1',   
        ['model'] = 'vwe_fugitive1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_fugitive1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_glendale1'] = {
        ['name'] = 'vwe_glendale1',   
        ['model'] = 'vwe_glendale1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_glendale1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_glendale2'] = {
        ['name'] = 'vwe_glendale2',   
        ['model'] = 'vwe_glendale2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_glendale2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_golem1'] = {
        ['name'] = 'vwe_golem1',   
        ['model'] = 'vwe_golem1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_golem1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_granger1'] = {
        ['name'] = 'vwe_granger1',   
        ['model'] = 'vwe_granger1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_granger1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_granger2'] = {
        ['name'] = 'vwe_granger2',   
        ['model'] = 'vwe_granger2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_granger2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_granger3'] = {
        ['name'] = 'vwe_granger3',   
        ['model'] = 'vwe_granger3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_granger3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_granger4'] = {
        ['name'] = 'vwe_granger4',   
        ['model'] = 'vwe_granger4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_granger4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_greenwood1'] = {
        ['name'] = 'vwe_greenwood1',   
        ['model'] = 'vwe_greenwood1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_greenwood1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_gresley1'] = {
        ['name'] = 'vwe_gresley1',   
        ['model'] = 'vwe_gresley1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_gresley1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_hachura1'] = {
        ['name'] = 'vwe_hachura1',   
        ['model'] = 'vwe_hachura1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_hachura1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_hades1'] = {
        ['name'] = 'vwe_hades1',   
        ['model'] = 'vwe_hades1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_hades1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_hauler1'] = {
        ['name'] = 'vwe_hauler1',   
        ['model'] = 'vwe_hauler1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_hauler1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_haulmaster1'] = {
        ['name'] = 'vwe_haulmaster1',   
        ['model'] = 'vwe_haulmaster1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_haulmaster1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_haulmaster2'] = {
        ['name'] = 'vwe_haulmaster2',   
        ['model'] = 'vwe_haulmaster2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_haulmaster2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_hellion1'] = {
        ['name'] = 'vwe_hellion1',   
        ['model'] = 'vwe_hellion1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_hellion1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_infernus1'] = {
        ['name'] = 'vwe_infernus1',   
        ['model'] = 'vwe_infernus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_infernus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_infernus2'] = {
        ['name'] = 'vwe_infernus2',   
        ['model'] = 'vwe_infernus2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_infernus2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_issi1'] = {
        ['name'] = 'vwe_issi1',   
        ['model'] = 'vwe_issi1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_issi1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_jester1'] = {
        ['name'] = 'vwe_jester1',   
        ['model'] = 'vwe_jester1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_jester1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_journey1'] = {
        ['name'] = 'vwe_journey1',   
        ['model'] = 'vwe_journey1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_journey1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_juggernaut1'] = {
        ['name'] = 'vwe_juggernaut1',   
        ['model'] = 'vwe_juggernaut1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_juggernaut1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_kenshin1'] = {
        ['name'] = 'vwe_kenshin1',   
        ['model'] = 'vwe_kenshin1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_kenshin1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_kuroi1'] = {
        ['name'] = 'vwe_kuroi1',   
        ['model'] = 'vwe_kuroi1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_kuroi1',   
        ['shop'] = 'pdm',   
    },    
    ['vwe_kuruma1'] = {
        ['name'] = 'vwe_kuruma1',   
        ['model'] = 'vwe_kuruma1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_kuruma1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_landroamer1'] = {
        ['name'] = 'vwe_landroamer1',   
        ['model'] = 'vwe_landroamer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_landroamer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_lazer1'] = {
        ['name'] = 'vwe_lazer1',   
        ['model'] = 'vwe_lazer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_lazer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_limo1'] = {
        ['name'] = 'vwe_limo1',   
        ['model'] = 'vwe_limo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_limo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_longpath1'] = {
        ['name'] = 'vwe_longpath1',   
        ['model'] = 'vwe_longpath1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_longpath1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_majimagt1'] = {
        ['name'] = 'vwe_majimagt1',   
        ['model'] = 'vwe_majimagt1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_majimagt1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mammatus1'] = {
        ['name'] = 'vwe_mammatus1',   
        ['model'] = 'vwe_mammatus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mammatus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_maverick1'] = {
        ['name'] = 'vwe_maverick1',   
        ['model'] = 'vwe_maverick1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_maverick1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_merit1'] = {
        ['name'] = 'vwe_merit1',   
        ['model'] = 'vwe_merit1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_merit1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mesa1'] = {
        ['name'] = 'vwe_mesa1',   
        ['model'] = 'vwe_mesa1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mesa1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mesa2'] = {
        ['name'] = 'vwe_mesa2',   
        ['model'] = 'vwe_mesa2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mesa2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_meteor1'] = {
        ['name'] = 'vwe_meteor1',   
        ['model'] = 'vwe_meteor1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_meteor1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mf1'] = {
        ['name'] = 'vwe_mf1',   
        ['model'] = 'vwe_mf1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mf1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mf12'] = {
        ['name'] = 'vwe_mf12',   
        ['model'] = 'vwe_mf12',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mf12',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_minivan1'] = {
        ['name'] = 'vwe_minivan1',   
        ['model'] = 'vwe_minivan1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_minivan1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mixer1'] = {
        ['name'] = 'vwe_mixer1',   
        ['model'] = 'vwe_mixer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mixer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_molecule1'] = {
        ['name'] = 'vwe_molecule1',   
        ['model'] = 'vwe_molecule1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_molecule1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_monroe1'] = {
        ['name'] = 'vwe_monroe1',   
        ['model'] = 'vwe_monroe1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_monroe1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_moonbeam1'] = {
        ['name'] = 'vwe_moonbeam1',   
        ['model'] = 'vwe_moonbeam1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_moonbeam1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mule1'] = {
        ['name'] = 'vwe_mule1',   
        ['model'] = 'vwe_mule1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mule1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mule2'] = {
        ['name'] = 'vwe_mule2',   
        ['model'] = 'vwe_mule2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mule2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mule3'] = {
        ['name'] = 'vwe_mule3',   
        ['model'] = 'vwe_mule3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mule3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_mule4'] = {
        ['name'] = 'vwe_mule4',   
        ['model'] = 'vwe_mule4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_mule4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_nebula1'] = {
        ['name'] = 'vwe_nebula1',   
        ['model'] = 'vwe_nebula1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_nebula1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_nebula2'] = {
        ['name'] = 'vwe_nebula2',   
        ['model'] = 'vwe_nebula2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_nebula2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_niner1'] = {
        ['name'] = 'vwe_niner1',   
        ['model'] = 'vwe_niner1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_niner1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_packer1'] = {
        ['name'] = 'vwe_packer1',   
        ['model'] = 'vwe_packer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_packer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_panto1'] = {
        ['name'] = 'vwe_panto1',   
        ['model'] = 'vwe_panto1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_panto1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_patriot1'] = {
        ['name'] = 'vwe_patriot1',   
        ['model'] = 'vwe_patriot1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_patriot1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_patriot2'] = {
        ['name'] = 'vwe_patriot2',   
        ['model'] = 'vwe_patriot2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_patriot2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_phantom1'] = {
        ['name'] = 'vwe_phantom1',   
        ['model'] = 'vwe_phantom1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_phantom1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_picador1'] = {
        ['name'] = 'vwe_picador1',   
        ['model'] = 'vwe_picador1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_picador1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_picador2'] = {
        ['name'] = 'vwe_picador2',   
        ['model'] = 'vwe_picador2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_picador2',   
        ['shop'] = 'pdm',   
    },        
    ['vwe_pony1'] = {
        ['name'] = 'vwe_pony1',   
        ['model'] = 'vwe_pony1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_pony1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_pony2'] = {
        ['name'] = 'vwe_pony2',   
        ['model'] = 'vwe_pony2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_pony2',   
        ['shop'] = 'pdm',   
    },    
    ['vwe_pounder1'] = {
        ['name'] = 'vwe_pounder1',   
        ['model'] = 'vwe_pounder1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_pounder1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_radi1'] = {
        ['name'] = 'vwe_radi1',   
        ['model'] = 'vwe_radi1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_radi1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_raider1'] = {
        ['name'] = 'vwe_raider1',   
        ['model'] = 'vwe_raider1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_raider1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ramptruck1'] = {
        ['name'] = 'vwe_ramptruck1',   
        ['model'] = 'vwe_ramptruck1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ramptruck1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ramptruck2'] = {
        ['name'] = 'vwe_ramptruck2',   
        ['model'] = 'vwe_ramptruck2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ramptruck2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rancher1'] = {
        ['name'] = 'vwe_rancher1',   
        ['model'] = 'vwe_rancher1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rancher1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rancher2'] = {
        ['name'] = 'vwe_rancher2',   
        ['model'] = 'vwe_rancher2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rancher2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rancher3'] = {
        ['name'] = 'vwe_rancher3',   
        ['model'] = 'vwe_rancher3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rancher3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rancherxl1'] = {
        ['name'] = 'vwe_rancherxl1',   
        ['model'] = 'vwe_rancherxl1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rancherxl1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ratloader1'] = {
        ['name'] = 'vwe_ratloader1',   
        ['model'] = 'vwe_ratloader1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ratloader1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_razor1'] = {
        ['name'] = 'vwe_razor1',   
        ['model'] = 'vwe_razor1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_razor1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rebel1'] = {
        ['name'] = 'vwe_rebel1',   
        ['model'] = 'vwe_rebel1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rebel1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rebel2'] = {
        ['name'] = 'vwe_rebel2',   
        ['model'] = 'vwe_rebel2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rebel2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rebel3'] = {
        ['name'] = 'vwe_rebel3',   
        ['model'] = 'vwe_rebel3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rebel3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rebel4'] = {
        ['name'] = 'vwe_rebel4',   
        ['model'] = 'vwe_rebel4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rebel4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_recursion1'] = {
        ['name'] = 'vwe_recursion1',   
        ['model'] = 'vwe_recursion1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_recursion1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_regina1'] = {
        ['name'] = 'vwe_regina1',   
        ['model'] = 'vwe_regina1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_regina1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_riata1'] = {
        ['name'] = 'vwe_riata1',   
        ['model'] = 'vwe_riata1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_riata1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_riata2'] = {
        ['name'] = 'vwe_riata2',   
        ['model'] = 'vwe_riata2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_riata2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_riata3'] = {
        ['name'] = 'vwe_riata3',   
        ['model'] = 'vwe_riata3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_riata3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_roadkiller1'] = {
        ['name'] = 'vwe_roadkiller1',   
        ['model'] = 'vwe_roadkiller1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_roadkiller1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rom1'] = {
        ['name'] = 'vwe_rom1',   
        ['model'] = 'vwe_rom1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rom1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ruiner1'] = {
        ['name'] = 'vwe_ruiner1',   
        ['model'] = 'vwe_ruiner1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ruiner1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ruiner2'] = {
        ['name'] = 'vwe_ruiner2',   
        ['model'] = 'vwe_ruiner2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ruiner2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rumpo1'] = {
        ['name'] = 'vwe_rumpo1',   
        ['model'] = 'vwe_rumpo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rumpo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_rumpo2'] = {
        ['name'] = 'vwe_rumpo2',   
        ['model'] = 'vwe_rumpo2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_rumpo2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_s2301'] = {
        ['name'] = 'vwe_s2301',   
        ['model'] = 'vwe_s2301',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_s2301',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sabot1'] = {
        ['name'] = 'vwe_sabot1',   
        ['model'] = 'vwe_sabot1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sabot1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler1'] = {
        ['name'] = 'vwe_sadler1',   
        ['model'] = 'vwe_sadler1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler2'] = {
        ['name'] = 'vwe_sadler2',   
        ['model'] = 'vwe_sadler2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler3'] = {
        ['name'] = 'vwe_sadler3',   
        ['model'] = 'vwe_sadler3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler4'] = {
        ['name'] = 'vwe_sadler4',   
        ['model'] = 'vwe_sadler4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler5'] = {
        ['name'] = 'vwe_sadler5',   
        ['model'] = 'vwe_sadler5',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler5',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler6'] = {
        ['name'] = 'vwe_sadler6',   
        ['model'] = 'vwe_sadler6',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler6',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sadler7'] = {
        ['name'] = 'vwe_sadler7',   
        ['model'] = 'vwe_sadler7',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sadler7',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sandking1'] = {
        ['name'] = 'vwe_sandking1',   
        ['model'] = 'vwe_sandking1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sandking1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sandking2'] = {
        ['name'] = 'vwe_sandking2',   
        ['model'] = 'vwe_sandking2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sandking2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_savestra1'] = {
        ['name'] = 'vwe_savestra1',   
        ['model'] = 'vwe_savestra1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_savestra1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sbus1'] = {
        ['name'] = 'vwe_sbus1',   
        ['model'] = 'vwe_sbus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sbus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sbus2'] = {
        ['name'] = 'vwe_sbus2',   
        ['model'] = 'vwe_sbus2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sbus2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_scamp1'] = {
        ['name'] = 'vwe_scamp1',   
        ['model'] = 'vwe_scamp1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_scamp1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_schwartzer1'] = {
        ['name'] = 'vwe_schwartzer1',   
        ['model'] = 'vwe_schwartzer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_schwartzer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_schwartzer2'] = {
        ['name'] = 'vwe_schwartzer2',   
        ['model'] = 'vwe_schwartzer2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_schwartzer2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_scout1'] = {
        ['name'] = 'vwe_scout1',   
        ['model'] = 'vwe_scout1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_scout1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_seminole1'] = {
        ['name'] = 'vwe_seminole1',   
        ['model'] = 'vwe_seminole1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_seminole1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_seminole2'] = {
        ['name'] = 'vwe_seminole2',   
        ['model'] = 'vwe_seminole2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_seminole2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sentinel1'] = {
        ['name'] = 'vwe_sentinel1',   
        ['model'] = 'vwe_sentinel1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sentinel1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_seraph1'] = {
        ['name'] = 'vwe_seraph1',   
        ['model'] = 'vwe_seraph1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_seraph1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_serena1'] = {
        ['name'] = 'vwe_serena1',   
        ['model'] = 'vwe_serena1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_serena1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sigma2'] = {
        ['name'] = 'vwe_sigma2',   
        ['model'] = 'vwe_sigma2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sigma2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sigma3'] = {
        ['name'] = 'vwe_sigma3',   
        ['model'] = 'vwe_sigma3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sigma3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_slamvan1'] = {
        ['name'] = 'vwe_slamvan1',   
        ['model'] = 'vwe_slamvan1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_slamvan1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_slasher1'] = {
        ['name'] = 'vwe_slasher1',   
        ['model'] = 'vwe_slasher1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_slasher1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_slave1'] = {
        ['name'] = 'vwe_slave1',   
        ['model'] = 'vwe_slave1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_slave1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sparrow1'] = {
        ['name'] = 'vwe_sparrow1',   
        ['model'] = 'vwe_sparrow1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sparrow1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_speedo1'] = {
        ['name'] = 'vwe_speedo1',   
        ['model'] = 'vwe_speedo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_speedo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_speedo2'] = {
        ['name'] = 'vwe_speedo2',   
        ['model'] = 'vwe_speedo2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_speedo2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_spirit1'] = {
        ['name'] = 'vwe_spirit1',   
        ['model'] = 'vwe_spirit1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_spirit1',   
        ['shop'] = 'pdm',   
    },    
    ['vwe_spritzer1'] = {
        ['name'] = 'vwe_spritzer1',   
        ['model'] = 'vwe_spritzer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_spritzer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_squaddie1'] = {
        ['name'] = 'vwe_squaddie1',   
        ['model'] = 'vwe_squaddie1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_squaddie1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_squaddie2'] = {
        ['name'] = 'vwe_squaddie2',   
        ['model'] = 'vwe_squaddie2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_squaddie2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stairtruck1'] = {
        ['name'] = 'vwe_stairtruck1',   
        ['model'] = 'vwe_stairtruck1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stairtruck1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stanier1'] = {
        ['name'] = 'vwe_stanier1',   
        ['model'] = 'vwe_stanier1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stanier1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stdstanier1'] = {
        ['name'] = 'vwe_stdstanier1',   
        ['model'] = 'vwe_stdstanier1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stdstanier1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_steed1'] = {
        ['name'] = 'vwe_steed1',   
        ['model'] = 'vwe_steed1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_steed1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_steed2'] = {
        ['name'] = 'vwe_steed2',   
        ['model'] = 'vwe_steed2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_steed2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_steed3'] = {
        ['name'] = 'vwe_steed3',   
        ['model'] = 'vwe_steed3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_steed3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stockade1'] = {
        ['name'] = 'vwe_stockade1',   
        ['model'] = 'vwe_stockade1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stockade1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stratum1'] = {
        ['name'] = 'vwe_stratum1',   
        ['model'] = 'vwe_stratum1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stratum1',   
        ['shop'] = 'pdm',   
    },    
    ['vwe_stratum2'] = {
        ['name'] = 'vwe_stratum2',   
        ['model'] = 'vwe_stratum2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stratum2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_streiter1'] = {
        ['name'] = 'vwe_streiter1',   
        ['model'] = 'vwe_streiter1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_streiter1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_stretch1'] = {
        ['name'] = 'vwe_stretch1',   
        ['model'] = 'vwe_stretch1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_stretch1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sultan1'] = {
        ['name'] = 'vwe_sultan1',   
        ['model'] = 'vwe_sultan1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sultan1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sultan2'] = {
        ['name'] = 'vwe_sultan2',   
        ['model'] = 'vwe_sultan2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sultan2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sultanrs1'] = {
        ['name'] = 'vwe_sultanrs1',   
        ['model'] = 'vwe_sultanrs1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sultanrs1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sultanrs2'] = {
        ['name'] = 'vwe_sultanrs2',   
        ['model'] = 'vwe_sultanrs2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sultanrs2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_sultanrs3'] = {
        ['name'] = 'vwe_sultanrs3',   
        ['model'] = 'vwe_sultanrs3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_sultanrs3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_supergts1'] = {
        ['name'] = 'vwe_supergts1',   
        ['model'] = 'vwe_supergts1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_supergts1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_surano1'] = {
        ['name'] = 'vwe_surano1',   
        ['model'] = 'vwe_surano1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_surano1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_surfer1'] = {
        ['name'] = 'vwe_surfer1',   
        ['model'] = 'vwe_surfer1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_surfer1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_surge1'] = {
        ['name'] = 'vwe_surge1',   
        ['model'] = 'vwe_surge1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_surge1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tachyon1'] = {
        ['name'] = 'vwe_tachyon1',   
        ['model'] = 'vwe_tachyon1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tachyon1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tailgater1'] = {
        ['name'] = 'vwe_tailgater1',   
        ['model'] = 'vwe_tailgater1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tailgater1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tailgater2'] = {
        ['name'] = 'vwe_tailgater2',   
        ['model'] = 'vwe_tailgater2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tailgater2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tailgater3'] = {
        ['name'] = 'vwe_tailgater3',   
        ['model'] = 'vwe_tailgater3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tailgater3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tampa1'] = {
        ['name'] = 'vwe_tampa1',   
        ['model'] = 'vwe_tampa1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tampa1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tanker1'] = {
        ['name'] = 'vwe_tanker1',   
        ['model'] = 'vwe_tanker1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tanker1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tanker2'] = {
        ['name'] = 'vwe_tanker2',   
        ['model'] = 'vwe_tanker2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tanker2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_taxi1'] = {
        ['name'] = 'vwe_taxi1',   
        ['model'] = 'vwe_taxi1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_taxi1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_templar1'] = {
        ['name'] = 'vwe_templar1',   
        ['model'] = 'vwe_templar1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_templar1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_torrence1'] = {
        ['name'] = 'vwe_torrence1',   
        ['model'] = 'vwe_torrence1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_torrence1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_towtruck1'] = {
        ['name'] = 'vwe_towtruck1',   
        ['model'] = 'vwe_towtruck1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_towtruck1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tr1'] = {
        ['name'] = 'vwe_tr1',   
        ['model'] = 'vwe_tr1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tr1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tractor1'] = {
        ['name'] = 'vwe_tractor1',   
        ['model'] = 'vwe_tractor1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tractor1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailercast1'] = {
        ['name'] = 'vwe_trailercast1',   
        ['model'] = 'vwe_trailercast1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailercast1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailerdump1'] = {
        ['name'] = 'vwe_trailerdump1',   
        ['model'] = 'vwe_trailerdump1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailerdump1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailerdump2'] = {
        ['name'] = 'vwe_trailerdump2',   
        ['model'] = 'vwe_trailerdump2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailerdump2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailerdump3'] = {
        ['name'] = 'vwe_trailerdump3',   
        ['model'] = 'vwe_trailerdump3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailerdump3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailerlogs1'] = {
        ['name'] = 'vwe_trailerlogs1',   
        ['model'] = 'vwe_trailerlogs1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailerlogs1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailers1'] = {
        ['name'] = 'vwe_trailers1',   
        ['model'] = 'vwe_trailers1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailers1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailers2'] = {
        ['name'] = 'vwe_trailers2',   
        ['model'] = 'vwe_trailers2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailers2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trailers3'] = {
        ['name'] = 'vwe_trailers3',   
        ['model'] = 'vwe_trailers3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trailers3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_trash1'] = {
        ['name'] = 'vwe_trash1',   
        ['model'] = 'vwe_trash1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_trash1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tulip1'] = {
        ['name'] = 'vwe_tulip1',   
        ['model'] = 'vwe_tulip1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tulip1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_turismo1'] = {
        ['name'] = 'vwe_turismo1',   
        ['model'] = 'vwe_turismo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_turismo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_tyrus1'] = {
        ['name'] = 'vwe_tyrus1',   
        ['model'] = 'vwe_tyrus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_tyrus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_uranus1'] = {
        ['name'] = 'vwe_uranus1',   
        ['model'] = 'vwe_uranus1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_uranus1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_urban1'] = {
        ['name'] = 'vwe_urban1',   
        ['model'] = 'vwe_urban1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_urban1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_utillitruck1'] = {
        ['name'] = 'vwe_utillitruck1',   
        ['model'] = 'vwe_utillitruck1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_utillitruck1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_utillitruck2'] = {
        ['name'] = 'vwe_utillitruck2',   
        ['model'] = 'vwe_utillitruck2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_utillitruck2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_utillitruck3'] = {
        ['name'] = 'vwe_utillitruck3',   
        ['model'] = 'vwe_utillitruck3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_utillitruck3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_ventoso1'] = {
        ['name'] = 'vwe_ventoso1',   
        ['model'] = 'vwe_ventoso1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_ventoso1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_verin1'] = {
        ['name'] = 'vwe_verin1',   
        ['model'] = 'vwe_verin1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_verin1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vertice1'] = {
        ['name'] = 'vwe_vertice1',   
        ['model'] = 'vwe_vertice1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vertice1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vesper1'] = {
        ['name'] = 'vwe_vesper1',   
        ['model'] = 'vwe_vesper1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vesper1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vigero1'] = {
        ['name'] = 'vwe_vigero1',   
        ['model'] = 'vwe_vigero1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vigero1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vincent1'] = {
        ['name'] = 'vwe_vincent1',   
        ['model'] = 'vwe_vincent1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vincent1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_voodoo1'] = {
        ['name'] = 'vwe_voodoo1',   
        ['model'] = 'vwe_voodoo1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_voodoo1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vor1 bpillow2+ihifr'] = {
        ['name'] = 'vwe_vor1 bpillow2+ihifr',   
        ['model'] = 'vwe_vor1 bpillow2+ihifr',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vor1 bpillow2+ihifr',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_vorstand1'] = {
        ['name'] = 'vwe_vorstand1',   
        ['model'] = 'vwe_vorstand1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_vorstand1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_warrener1'] = {
        ['name'] = 'vwe_warrener1',   
        ['model'] = 'vwe_warrener1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_warrener1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_washington1'] = {
        ['name'] = 'vwe_washington1',   
        ['model'] = 'vwe_washington1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_washington1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_watertanker1'] = {
        ['name'] = 'vwe_watertanker1',   
        ['model'] = 'vwe_watertanker1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_watertanker1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_wintergreen1'] = {
        ['name'] = 'vwe_wintergreen1',   
        ['model'] = 'vwe_wintergreen1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_wintergreen1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yankee1'] = {
        ['name'] = 'vwe_yankee1',   
        ['model'] = 'vwe_yankee1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yankee1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yankee2'] = {
        ['name'] = 'vwe_yankee2',   
        ['model'] = 'vwe_yankee2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yankee2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yankee3'] = {
        ['name'] = 'vwe_yankee3',   
        ['model'] = 'vwe_yankee3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yankee3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemite1'] = {
        ['name'] = 'vwe_yosemite1',   
        ['model'] = 'vwe_yosemite1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemite1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemite2'] = {
        ['name'] = 'vwe_yosemite2',   
        ['model'] = 'vwe_yosemite2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemite2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemite3'] = {
        ['name'] = 'vwe_yosemite3',   
        ['model'] = 'vwe_yosemite3',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemite3',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemite4'] = {
        ['name'] = 'vwe_yosemite4',   
        ['model'] = 'vwe_yosemite4',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemite4',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemite5'] = {
        ['name'] = 'vwe_yosemite5',   
        ['model'] = 'vwe_yosemite5',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemite5',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemitexl1'] = {
        ['name'] = 'vwe_yosemitexl1',   
        ['model'] = 'vwe_yosemitexl1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemitexl1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_yosemitexl2'] = {
        ['name'] = 'vwe_yosemitexl2',   
        ['model'] = 'vwe_yosemitexl2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_yosemitexl2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_youga1'] = {
        ['name'] = 'vwe_youga1',   
        ['model'] = 'vwe_youga1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_youga1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_zion1'] = {
        ['name'] = 'vwe_zion1',   
        ['model'] = 'vwe_zion1',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_zion1',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_zion2'] = {
        ['name'] = 'vwe_zion2',   
        ['model'] = 'vwe_zion2',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_zion2',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_zr1501'] = {
        ['name'] = 'vwe_zr1501',   
        ['model'] = 'vwe_zr1501',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_zr1501',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_zr3501'] = {
        ['name'] = 'vwe_zr3501',   
        ['model'] = 'vwe_zr3501',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_zr3501',   
        ['shop'] = 'pdm',   
    },   
    ['vwe_zr3801'] = {
        ['name'] = 'vwe_zr3801',   
        ['model'] = 'vwe_zr3801',   
        ['price'] = 20000,   
        ['category'] = 'compacts',   
        ['categoryLabel'] = 'Compacts',   
        ['hash'] = 'vwe_zr3801',   
        ['shop'] = 'pdm',   
    },   
 

    -- Vanilla Works END